import type { SelectOption } from "@/src/components/ui/input/searchInput/SelectField";

export type DirectorNoticeStateKey =
    | "scotland"
    | "northern-ireland"
    | "isle-of-man"
    | "north-west"
    | "north-east"
    | "yorkshire-and-the-humber"
    | "east-midlands"
    | "west-midlands"
    | "wales"
    | "eastern"
    | "london"
    | "south-west"
    | "south-east";

const STATE_LABELS: Record<DirectorNoticeStateKey, string> = {
    scotland: "Scotland",
    "northern-ireland": "Northern Ireland",
    "isle-of-man": "Isle of Man",
    "north-west": "North West",
    "north-east": "North East",
    "yorkshire-and-the-humber": "Yorkshire and the Humber",
    "east-midlands": "East Midlands",
    "west-midlands": "West Midlands",
    wales: "Wales",
    eastern: "Eastern",
    london: "London",
    "south-west": "South West",
    "south-east": "South East",
};

export const DIRECTOR_NOTICE_TOWN_LIST: Record<DirectorNoticeStateKey, SelectOption[]> = {
    scotland: [
        { value: "aberdeen", label: "Aberdeen" },
        { value: "aberdeenshire", label: "Aberdeenshire" },
        { value: "aboyne", label: "Aboyne" },
        { value: "airdrie", label: "Airdrie" },
        { value: "annan", label: "Annan" },
        { value: "arnbroath", label: "Arbroath" },
        { value: "ayr", label: "Ayr" },
        { value: "bathgate", label: "Bathgate" },
        { value: "cumbernauld", label: "Cumbernauld" },
        { value: "dundee", label: "Dundee" },
        { value: "dunfermline", label: "Dunfermline" },
        { value: "edinburgh", label: "Edinburgh" },
        { value: "elgin", label: "Elgin" },
        { value: "falkirk", label: "Falkirk" },
        { value: "fort-william", label: "Fort William" },
        { value: "galashiels", label: "Galashiels" },
        { value: "glasgow", label: "Glasgow" },
        { value: "greenock", label: "Greenock" },
        { value: "hamilton", label: "Hamilton" },
        { value: "inverness", label: "Inverness" },
        { value: "kilmarnock", label: "Kilmarnock" },
        { value: "kirkcaldy", label: "Kirkcaldy" },
        { value: "livingston", label: "Livingston" },
        { value: "motherwell", label: "Motherwell" },
        { value: "paisley", label: "Paisley" },
        { value: "perth", label: "Perth" },
        { value: "stirling", label: "Stirling" },
        { value: "wick", label: "Wick" },
    ],
    "northern-ireland": [
        { value: "antrim", label: "Antrim" },
        { value: "armagh", label: "Armagh" },
        { value: "ballymena", label: "Ballymena" },
        { value: "ballymoney", label: "Ballymoney" },
        { value: "banbridge", label: "Banbridge" },
        { value: "bangor", label: "Bangor" },
        { value: "belfast", label: "Belfast" },
        { value: "carrickfergus", label: "Carrickfergus" },
        { value: "coleraine", label: "Coleraine" },
        { value: "cookstown", label: "Cookstown" },
        { value: "craigavon", label: "Craigavon" },
        { value: "derry", label: "Derry" },
        { value: "downpatrick", label: "Downpatrick" },
        { value: "dungannon", label: "Dungannon" },
        { value: "enniskillen", label: "Enniskillen" },
        { value: "holywood", label: "Holywood" },
        { value: "larne", label: "Larne" },
        { value: "limavady", label: "Limavady" },
        { value: "lisburn", label: "Lisburn" },
        { value: "magherafelt", label: "Magherafelt" },
        { value: "newry", label: "Newry" },
        { value: "newtownabbey", label: "Newtownabbey" },
        { value: "newtownards", label: "Newtownards" },
        { value: "omagh", label: "Omagh" },
        { value: "portadown", label: "Portadown" },
        { value: "portrush", label: "Portrush" },
        { value: "strabane", label: "Strabane" },
    ],
    "isle-of-man": [
        { value: "andreas", label: "Andreas" },
        { value: "ballasalla", label: "Ballasalla" },
        { value: "ballaugh", label: "Ballaugh" },
        { value: "braddan", label: "Braddan" },
        { value: "bridgetown", label: "Bridgetown" },
        { value: "castletown", label: "Castletown" },
        { value: "colby", label: "Colby" },
        { value: "crosby", label: "Crosby" },
        { value: "douglas", label: "Douglas" },
        { value: "foxdale", label: "Foxdale" },
        { value: "jurby", label: "Jurby" },
        { value: "laxey", label: "Laxey" },
        { value: "onchan", label: "Onchan" },
        { value: "peel", label: "Peel" },
        { value: "port-erin", label: "Port Erin" },
        { value: "port-mary", label: "Port Mary" },
        { value: "port-st-mary", label: "Port St Mary" },
        { value: "ramsey", label: "Ramsey" },
        { value: "santon", label: "Santon" },
        { value: "st-johns", label: "St Johns" },
        { value: "sulby", label: "Sulby" },
        { value: "union-mills", label: "Union Mills" },
    ],
    "north-west": [
        { value: "altrincham", label: "Altrincham" },
        { value: "bacup", label: "Bacup" },
        { value: "barrow-in-furness", label: "Barrow-in-Furness" },
        { value: "blackburn", label: "Blackburn" },
        { value: "blackpool", label: "Blackpool" },
        { value: "bolton", label: "Bolton" },
        { value: "burnley", label: "Burnley" },
        { value: "bury", label: "Bury" },
        { value: "carlisle", label: "Carlisle" },
        { value: "chester", label: "Chester" },
        { value: "chorley", label: "Chorley" },
        { value: "crewe", label: "Crewe" },
        { value: "ellesmere-port", label: "Ellesmere Port" },
        { value: "kendal", label: "Kendal" },
        { value: "lancaster", label: "Lancaster" },
        { value: "liverpool", label: "Liverpool" },
        { value: "macclesfield", label: "Macclesfield" },
        { value: "manchester", label: "Manchester" },
        { value: "oldham", label: "Oldham" },
        { value: "preston", label: "Preston" },
        { value: "rochdale", label: "Rochdale" },
        { value: "salford", label: "Salford" },
        { value: "stockport", label: "Stockport" },
        { value: "st-helens", label: "St Helens" },
        { value: "warrington", label: "Warrington" },
        { value: "wigan", label: "Wigan" },
        { value: "workington", label: "Workington" },
    ],
    "north-east": [
        { value: "alnwick", label: "Alnwick" },
        { value: "berwick-upon-tweed", label: "Berwick-upon-Tweed" },
        { value: "billingham", label: "Billingham" },
        { value: "bishop-auckland", label: "Bishop Auckland" },
        { value: "blyth", label: "Blyth" },
        { value: "chester-le-street", label: "Chester-le-Street" },
        { value: "consett", label: "Consett" },
        { value: "darlington", label: "Darlington" },
        { value: "durham", label: "Durham" },
        { value: "gateshead", label: "Gateshead" },
        { value: "hartlepool", label: "Hartlepool" },
        { value: "hexham", label: "Hexham" },
        { value: "houghton-le-spring", label: "Houghton-le-Spring" },
        { value: "jarrow", label: "Jarrow" },
        { value: "middlesbrough", label: "Middlesbrough" },
        { value: "newcastle-upon-tyne", label: "Newcastle upon Tyne" },
        { value: "north-shields", label: "North Shields" },
        { value: "peterlee", label: "Peterlee" },
        { value: "redcar", label: "Redcar" },
        { value: "seaham", label: "Seaham" },
        { value: "south-shields", label: "South Shields" },
        { value: "stockton-on-tees", label: "Stockton-on-Tees" },
        { value: "sunderland", label: "Sunderland" },
        { value: "washington", label: "Washington" },
        { value: "whitley-bay", label: "Whitley Bay" },
    ],
    "yorkshire-and-the-humber": [
        { value: "barnsley", label: "Barnsley" },
        { value: "beverley", label: "Beverley" },
        { value: "bradford", label: "Bradford" },
        { value: "brighouse", label: "Brighouse" },
        { value: "castleford", label: "Castleford" },
        { value: "cleethorpes", label: "Cleethorpes" },
        { value: "doncaster", label: "Doncaster" },
        { value: "goole", label: "Goole" },
        { value: "halifax", label: "Halifax" },
        { value: "harrogate", label: "Harrogate" },
        { value: "huddersfield", label: "Huddersfield" },
        { value: "hull", label: "Kingston upon Hull" },
        { value: "keighley", label: "Keighley" },
        { value: "leeds", label: "Leeds" },
        { value: "pontefract", label: "Pontefract" },
        { value: "ripon", label: "Ripon" },
        { value: "rotherham", label: "Rotherham" },
        { value: "scarborough", label: "Scarborough" },
        { value: "selby", label: "Selby" },
        { value: "sheffield", label: "Sheffield" },
        { value: "shipley", label: "Shipley" },
        { value: "skegness", label: "Skegness" },
        { value: "todmorden", label: "Todmorden" },
        { value: "wakefield", label: "Wakefield" },
        { value: "york", label: "York" },
    ],
    "east-midlands": [
        { value: "alfreton", label: "Alfreton" },
        { value: "ashby-de-la-zouch", label: "Ashby-de-la-Zouch" },
        { value: "bakewell", label: "Bakewell" },
        { value: "belper", label: "Belper" },
        { value: "boston", label: "Boston" },
        { value: "burton-upon-trent", label: "Burton upon Trent" },
        { value: "chesterfield", label: "Chesterfield" },
        { value: "corby", label: "Corby" },
        { value: "derby", label: "Derby" },
        { value: "glossop", label: "Glossop" },
        { value: "grantham", label: "Grantham" },
        { value: "grimsby", label: "Grimsby" },
        { value: "heanor", label: "Heanor" },
        { value: "high-peak", label: "High Peak" },
        { value: "ilkeston", label: "Ilkeston" },
        { value: "leicester", label: "Leicester" },
        { value: "lincoln", label: "Lincoln" },
        { value: "loughborough", label: "Loughborough" },
        { value: "mansfield", label: "Mansfield" },
        { value: "melton-mowbray", label: "Melton Mowbray" },
        { value: "newark-on-trent", label: "Newark-on-Trent" },
        { value: "northampton", label: "Northampton" },
        { value: "nottingham", label: "Nottingham" },
        { value: "rutland", label: "Rutland" },
        { value: "skegness", label: "Skegness" },
        { value: "spalding", label: "Spalding" },
        { value: "stamford", label: "Stamford" },
        { value: "worksop", label: "Worksop" },
    ],
    "west-midlands": [
        { value: "birmingham", label: "Birmingham" },
        { value: "bromsgrove", label: "Bromsgrove" },
        { value: "burton-upon-trent", label: "Burton upon Trent" },
        { value: "cannock", label: "Cannock" },
        { value: "coventry", label: "Coventry" },
        { value: "dudley", label: "Dudley" },
        { value: "halesowen", label: "Halesowen" },
        { value: "hereford", label: "Hereford" },
        { value: "kidderminster", label: "Kidderminster" },
        { value: "leamington-spa", label: "Leamington Spa" },
        { value: "ludlow", label: "Ludlow" },
        { value: "newcastle-under-lyme", label: "Newcastle-under-Lyme" },
        { value: "nuneaton", label: "Nuneaton" },
        { value: "redditch", label: "Redditch" },
        { value: "rugby", label: "Rugby" },
        { value: "shrewsbury", label: "Shrewsbury" },
        { value: "solihull", label: "Solihull" },
        { value: "stafford", label: "Stafford" },
        { value: "stoke-on-trent", label: "Stoke-on-Trent" },
        { value: "stratford-upon-avon", label: "Stratford-upon-Avon" },
        { value: "sutton-coldfield", label: "Sutton Coldfield" },
        { value: "tamworth", label: "Tamworth" },
        { value: "telford", label: "Telford" },
        { value: "walsall", label: "Walsall" },
        { value: "warwick", label: "Warwick" },
        { value: "west-bromwich", label: "West Bromwich" },
        { value: "wolverhampton", label: "Wolverhampton" },
        { value: "worcester", label: "Worcester" },
    ],
    wales: [
        { value: "aberystwyth", label: "Aberystwyth" },
        { value: "bangor", label: "Bangor" },
        { value: "barry", label: "Barry" },
        { value: "bridgend", label: "Bridgend" },
        { value: "caernarfon", label: "Caernarfon" },
        { value: "cardiff", label: "Cardiff" },
        { value: "carmarthen", label: "Carmarthen" },
        { value: "colwyn-bay", label: "Colwyn Bay" },
        { value: "conwy", label: "Conwy" },
        { value: "cwmbran", label: "Cwmbran" },
        { value: "denbigh", label: "Denbigh" },
        { value: "holyhead", label: "Holyhead" },
        { value: "lampeter", label: "Lampeter" },
        { value: "llandudno", label: "Llandudno" },
        { value: "llanelli", label: "Llanelli" },
        { value: "llangollen", label: "Llangollen" },
        { value: "merthyr-tydfil", label: "Merthyr Tydfil" },
        { value: "milford-haven", label: "Milford Haven" },
        { value: "monmouth", label: "Monmouth" },
        { value: "neath", label: "Neath" },
        { value: "newport", label: "Newport" },
        { value: "newtown", label: "Newtown" },
        { value: "penarth", label: "Penarth" },
        { value: "pontypridd", label: "Pontypridd" },
        { value: "prestatyn", label: "Prestatyn" },
        { value: "rhyl", label: "Rhyl" },
        { value: "st-davids", label: "St Davids" },
        { value: "swansea", label: "Swansea" },
        { value: "tenby", label: "Tenby" },
        { value: "wrexham", label: "Wrexham" },
    ],
    eastern: [
        { value: "basildon", label: "Basildon" },
        { value: "bedford", label: "Bedford" },
        { value: "bishop-stortford", label: "Bishop's Stortford" },
        { value: "boston", label: "Boston" },
        { value: "brentwood", label: "Brentwood" },
        { value: "bristol", label: "Bristol" },
        { value: "bury-st-edmunds", label: "Bury St Edmunds" },
        { value: "cambridge", label: "Cambridge" },
        { value: "chelmsford", label: "Chelmsford" },
        { value: "colchester", label: "Colchester" },
        { value: "diss", label: "Diss" },
        { value: "ely", label: "Ely" },
        { value: "felixstowe", label: "Felixstowe" },
        { value: "great-yarmouth", label: "Great Yarmouth" },
        { value: "harlow", label: "Harlow" },
        { value: "hemel-hempstead", label: "Hemel Hempstead" },
        { value: "ipswich", label: "Ipswich" },
        { value: "kings-lynn", label: "King's Lynn" },
        { value: "luton", label: "Luton" },
        { value: "milton-keynes", label: "Milton Keynes" },
        { value: "newmarket", label: "Newmarket" },
        { value: "norwich", label: "Norwich" },
        { value: "peterborough", label: "Peterborough" },
        { value: "southend-on-sea", label: "Southend-on-Sea" },
        { value: "st-albans", label: "St Albans" },
        { value: "stevenage", label: "Stevenage" },
        { value: "watford", label: "Watford" },
        { value: "witham", label: "Witham" },
    ],
    london: [
        { value: "barking", label: "Barking" },
        { value: "barnet", label: "Barnet" },
        { value: "bexley", label: "Bexley" },
        { value: "brent", label: "Brent" },
        { value: "bromley", label: "Bromley" },
        { value: "camden", label: "Camden" },
        { value: "croydon", label: "Croydon" },
        { value: "ealing", label: "Ealing" },
        { value: "enfield", label: "Enfield" },
        { value: "greenwich", label: "Greenwich" },
        { value: "hackney", label: "Hackney" },
        { value: "hammersmith", label: "Hammersmith" },
        { value: "haringey", label: "Haringey" },
        { value: "harrow", label: "Harrow" },
        { value: "havering", label: "Havering" },
        { value: "hounslow", label: "Hounslow" },
        { value: "islington", label: "Islington" },
        { value: "kensington", label: "Kensington" },
        { value: "kingston-upon-thames", label: "Kingston upon Thames" },
        { value: "lambeth", label: "Lambeth" },
        { value: "lewisham", label: "Lewisham" },
        { value: "merton", label: "Merton" },
        { value: "newham", label: "Newham" },
        { value: "redbridge", label: "Redbridge" },
        { value: "richmond", label: "Richmond" },
        { value: "southwark", label: "Southwark" },
        { value: "sutton", label: "Sutton" },
        { value: "tower-hamlets", label: "Tower Hamlets" },
        { value: "waltham-forest", label: "Waltham Forest" },
        { value: "wandsworth", label: "Wandsworth" },
        { value: "westminster", label: "Westminster" },
    ],
    "south-west": [
        { value: "barnstaple", label: "Barnstaple" },
        { value: "bath", label: "Bath" },
        { value: "bodmin", label: "Bodmin" },
        { value: "bristol", label: "Bristol" },
        { value: "cheltenham", label: "Cheltenham" },
        { value: "chippenham", label: "Chippenham" },
        { value: "cirencester", label: "Cirencester" },
        { value: "dorchester", label: "Dorchester" },
        { value: "exeter", label: "Exeter" },
        { value: "falmouth", label: "Falmouth" },
        { value: "gloucester", label: "Gloucester" },
        { value: "helston", label: "Helston" },
        { value: "launceston", label: "Launceston" },
        { value: "newquay", label: "Newquay" },
        { value: "penzance", label: "Penzance" },
        { value: "peterborough", label: "Peterborough" },
        { value: "plymouth", label: "Plymouth" },
        { value: "poole", label: "Poole" },
        { value: "redruth", label: "Redruth" },
        { value: "salisbury", label: "Salisbury" },
        { value: "st-austell", label: "St Austell" },
        { value: "st-ives", label: "St Ives" },
        { value: "swindon", label: "Swindon" },
        { value: "taunton", label: "Taunton" },
        { value: "tewkesbury", label: "Tewkesbury" },
        { value: "torquay", label: "Torquay" },
        { value: "truro", label: "Truro" },
        { value: "warminster", label: "Warminster" },
        { value: "weston-super-mare", label: "Weston-super-Mare" },
        { value: "weymouth", label: "Weymouth" },
        { value: "yeovil", label: "Yeovil" },
    ],
    "south-east": [
        { value: "ashford", label: "Ashford" },
        { value: "aylesbury", label: "Aylesbury" },
        { value: "basingstoke", label: "Basingstoke" },
        { value: "brighton", label: "Brighton" },
        { value: "canterbury", label: "Canterbury" },
        { value: "chatham", label: "Chatham" },
        { value: "crawley", label: "Crawley" },
        { value: "dover", label: "Dover" },
        { value: "eastbourne", label: "Eastbourne" },
        { value: "folkestone", label: "Folkestone" },
        { value: "gillingham", label: "Gillingham" },
        { value: "guildford", label: "Guildford" },
        { value: "hastings", label: "Hastings" },
        { value: "high-wycombe", label: "High Wycombe" },
        { value: "maidstone", label: "Maidstone" },
        { value: "margate", label: "Margate" },
        { value: "newbury", label: "Newbury" },
        { value: "newport-isle-of-wight", label: "Newport (Isle of Wight)" },
        { value: "oxford", label: "Oxford" },
        { value: "portsmouth", label: "Portsmouth" },
        { value: "ramgate", label: "Ramsgate" },
        { value: "reading", label: "Reading" },
        { value: "reigate", label: "Reigate" },
        { value: "slough", label: "Slough" },
        { value: "southampton", label: "Southampton" },
        { value: "southend-on-sea", label: "Southend-on-Sea" },
        { value: "winchester", label: "Winchester" },
        { value: "windsor", label: "Windsor" },
        { value: "woking", label: "Woking" },
        { value: "wokingham", label: "Wokingham" },
        { value: "worthing", label: "Worthing" },
    ],
};

export const DIRECTOR_NOTICE_STATE_OPTIONS: SelectOption[] = (
    Object.keys(STATE_LABELS) as DirectorNoticeStateKey[]
).map((key) => ({
    value: key,
    label: STATE_LABELS[key],
}));
